<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_button-ace-f26-ddf</name>
   <tag></tag>
   <elementGuidId>a9dc8351-5a2d-4437-ac75-beb92172ae28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section >> internal:has-text=&quot;#1 email used worldwide AI-powered, secure, and easy to use email trusted by bil&quot;i >> internal:label=&quot;Get started with Google Workspace&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2059119-4d86-4f01-9206-f1e3bd2f143e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6cfe2a11-98fa-46ea-8780-fe336c7ec52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://workspace.google.com/business/signup/welcome?hl=en&amp;source=gafb-gmail-hero-en&amp;ga_region=noram&amp;ga_country=us&amp;ga_lang=en</value>
      <webElementGuid>8e05df35-62fd-40d5-a0c6-d29483bdb245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> button </value>
      <webElementGuid>3378b107-4065-4ddb-874a-e894ec074150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-event</name>
      <type>Main</type>
      <value>gmail: hero</value>
      <webElementGuid>f2b6a32c-bf54-417f-94bf-299628092db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-action</name>
      <type>Main</type>
      <value>trial cta</value>
      <webElementGuid>b828d6b2-40bd-4cff-9ed6-a2ca3dcee6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-label</name>
      <type>Main</type>
      <value>https://workspace.google.com/business/signup/welcome?hl=en</value>
      <webElementGuid>d412f9a8-3102-4373-a8c3-337b00f9e4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Get started with Google Workspace</value>
      <webElementGuid>dce29adf-fa34-4ff6-85f1-4ce24ffc2bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/a[@class=&quot;button&quot;]</value>
      <webElementGuid>3a22ffe3-325d-4001-a60a-26c10ea4c47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Gmail Private  Secure Email for Person_6b53a6/gws-button_Get started-rkspace-f26</value>
      <webElementGuid>272a37c0-1a6b-4071-91cb-82cdb24ef1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b7e2bca2-9cd2-442d-af00-87cbbd11882e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>799ce547-904e-46fd-b88e-a50bc8f9b54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://workspace.google.com/business/signup/welcome?hl=en&amp;source=gafb-gmail-hero-en&amp;ga_region=noram&amp;ga_country=us&amp;ga_lang=en')]</value>
      <webElementGuid>c4de560d-59fd-474c-9a9e-32e7be5b8674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://workspace.google.com/business/signup/welcome?hl=en&amp;source=gafb-gmail-hero-en&amp;ga_region=noram&amp;ga_country=us&amp;ga_lang=en']</value>
      <webElementGuid>e0a3b4ac-c59f-4175-a643-4b7d6978f2cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
