<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gws-button_Get started-rkspace-f26</name>
   <tag></tag>
   <elementGuidId>56a9a94a-3dee-4b95-a963-044d171fbc9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='m2']/div/div/div/div[2]/div/gws-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>gws-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section >> internal:has-text=&quot;#1 email used worldwide AI-powered, secure, and easy to use email trusted by bil&quot;i >> gws-button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gws-button</value>
      <webElementGuid>c53a2a65-ef5f-42ed-945c-bf6ba5a5232f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://workspace.google.com/business/signup/welcome?hl=en&amp;source=gafb-gmail-hero-en&amp;ga_region=noram&amp;ga_country=us&amp;ga_lang=en</value>
      <webElementGuid>08022c15-e37e-4c04-9514-6bfb606eaea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Get started with Google Workspace</value>
      <webElementGuid>d3eae211-2ca1-4403-b0bd-869512a7ba8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-event</name>
      <type>Main</type>
      <value>gmail: hero</value>
      <webElementGuid>3ed3ce0d-e35f-4795-93a7-40470ea413a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-label</name>
      <type>Main</type>
      <value>https://workspace.google.com/business/signup/welcome?hl=en</value>
      <webElementGuid>f2df1945-c64c-465e-b8a1-d095c2bdb9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-action</name>
      <type>Main</type>
      <value>trial cta</value>
      <webElementGuid>0bb81465-e80f-42c1-b376-508b0f205f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get started</value>
      <webElementGuid>028d43fe-7a6e-41ab-9aa1-3d611f44f6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m2&quot;)/div[1]/div[@class=&quot;_grid_vqvmf_2 _wrapper_djoel_2&quot;]/div[@class=&quot;_column_vqvmf_125 _content_djoel_40 _fixedRightPadding_djoel_91&quot;]/div[@class=&quot;_container_b2skv_227 _body_b2skv_2 _lg_b2skv_29 _body_djoel_100&quot;]/div[@class=&quot;_buttonGroup_dqfj5_2 _buttonGroupHorizontal_dqfj5_14 button-group horizontal&quot;]/gws-button[1]</value>
      <webElementGuid>1a2430ea-083d-4920-9c89-6cb1244f8b04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='m2']/div/div/div/div[2]/div/gws-button</value>
      <webElementGuid>e9d7d15d-13a2-4067-95fc-fd9ad5782828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#1 email used worldwide'])[1]/following::gws-button[1]</value>
      <webElementGuid>f3d1a499-b9a6-4fef-980e-3516ca85214d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin console'])[6]/following::gws-button[1]</value>
      <webElementGuid>2f02fb9e-3237-4830-a593-d3eacb255345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact sales'])[3]/preceding::gws-button[1]</value>
      <webElementGuid>5c2809d8-c281-4d8e-a3cc-1759a11a87e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore features'])[1]/preceding::gws-button[2]</value>
      <webElementGuid>e28baf36-c5b8-4223-86c0-6664b8eca2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gws-button</value>
      <webElementGuid>bc0f09c2-8bb0-4d81-b25a-871736540275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//gws-button[@href = 'https://workspace.google.com/business/signup/welcome?hl=en&amp;source=gafb-gmail-hero-en&amp;ga_region=noram&amp;ga_country=us&amp;ga_lang=en' and (text() = 'Get started' or . = 'Get started')]</value>
      <webElementGuid>e5f69325-61bd-4468-9e32-e6ef088d8398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
