<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_Solutions</name>
   <tag></tag>
   <elementGuidId>9f4268ca-197f-4bb7-beae-32e18ef57f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div[2]/div/details/summary</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.header__tablet-nav__left.header__nav > details.header__nav__group > summary.header__nav__group__button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Solutions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>dd1f5659-3510-458a-bffc-0d25ae34fe76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__nav__group__button </value>
      <webElementGuid>36a37af4-1c87-49b4-b390-42471c775d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-action</name>
      <type>Main</type>
      <value>solutions</value>
      <webElementGuid>77bc8a67-c54e-4e25-b142-094335ccdc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-event</name>
      <type>Main</type>
      <value>gmail: global nav</value>
      <webElementGuid>a11e0cd7-a4dd-4b3c-afb5-15328fd93285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-label</name>
      <type>Main</type>
      <value>in-page interaction</value>
      <webElementGuid>bbaab3c4-1a88-49d8-a368-977c4afff143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>event</name>
      <type>Main</type>
      <value>autotrack-data-g</value>
      <webElementGuid>71a4ef65-041e-4037-bd1e-dc6f395f5540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fa28f92-3351-4d44-85ea-708a45b812b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Solutions
                </value>
      <webElementGuid>7e27c7c3-25ec-4d06-ae18-d4af0f221275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/header[@class=&quot;header&quot;]/div[@class=&quot;header__tablet-nav header__content&quot;]/div[@class=&quot;header__tablet-nav__left header__nav&quot;]/details[@class=&quot;header__nav__group&quot;]/summary[@class=&quot;header__nav__group__button&quot;]</value>
      <webElementGuid>72d97f3a-6bea-4bcc-a27e-2cb57d8ff4b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div[2]/div/details/summary</value>
      <webElementGuid>789934c2-06d7-4d24-b22e-b2286c2acdd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get started'])[2]/following::summary[1]</value>
      <webElementGuid>28927338-5ec3-4af7-912e-5b0008ddd0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact sales'])[2]/following::summary[1]</value>
      <webElementGuid>0ba9e051-51e4-4b97-af08-d3b7a8a38ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solutions'])[5]/preceding::summary[1]</value>
      <webElementGuid>837d8dbd-3d68-4801-b1ec-1acede08c355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Individuals'])[3]/preceding::summary[1]</value>
      <webElementGuid>46c20276-2cae-42d2-9439-161b826c6999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/details/summary</value>
      <webElementGuid>6d24479b-15ea-46a6-a7db-89808e75414b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//summary[(text() = '
                  Solutions
                ' or . = '
                  Solutions
                ')]</value>
      <webElementGuid>84aa127f-8673-4294-9e62-09f3d3ffce7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
